# Generated by Django 6.0.4 on 2026-04-12 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steam_id', models.CharField(blank=True, null=True)),
                ('data', models.TextField()),
                ('log_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gmodlogs.logtype')),
            ],
        ),
    ]
