# Generated by Django 6.0.4 on 2026-04-26 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LogType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steam_id', models.CharField(blank=True, max_length=32, null=True)),
                ('steam_id64', models.CharField(blank=True, max_length=32, null=True)),
                ('nickname', models.CharField(blank=True, max_length=255, null=True)),
                ('data', models.TextField()),
                ('insertion_datetime', models.DateTimeField(auto_now_add=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gmodlogs.logaction')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gmodlogs.logtype')),
            ],
        ),
    ]
