# Generated by Django 6.0.4 on 2026-04-12 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmodlogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
            ],
        ),
        migrations.RenameField(
            model_name='log',
            old_name='log_type',
            new_name='type',
        ),
        migrations.AddField(
            model_name='log',
            name='action',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='gmodlogs.logaction'),
            preserve_default=False,
        ),
    ]
