# Generated by Django 6.0.4 on 2026-04-12 20:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmodlogs', '0002_logaction_rename_log_type_log_type_log_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='insertion_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='log',
            name='nickname',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='steam_id64',
            field=models.CharField(blank=True, null=True),
        ),
    ]
