[supervisord]
nodaemon=true
user=root

[program:redis]
command=redis-server --daemonize no
autostart=true
autorestart=true
user=root
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:gunicorn]
command=sh -c "python manage.py compilescss && python manage.py collectstatic --noinput && exec gunicorn --access-logfile - --workers 3 --bind 0.0.0.0:80 core.wsgi:application"
directory=/usr/src/gmod-logs-server/gmodlogs
autostart=true
environment=HOME="/tmp"
autorestart=true
user=root
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:celery-worker]
command=celery -A core worker -l info
directory=/usr/src/gmod-logs-server/gmodlogs
autostart=true
autorestart=true
user=root
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:celery-beat]
command=celery -A core beat -l info
directory=/usr/src/gmod-logs-server/gmodlogs
autostart=true
autorestart=true
user=root
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
